build:
  stage: build
  services: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    # CI_DOCKERHUB_AUTH=`echo -n $USERNAME:$TOKEN | base64`
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${CI_DOCKERHUB_AUTH}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination=${ACCOUNT}/${CI_PROJECT_NAME}:${CI_PIPELINE_IID} --destination=${ACCOUNT}/${CI_PROJECT_NAME}:latest
