build:
  stage: build
  services: []
  variables:
    TAG: ${CI_COMMIT_REF_NAME}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${CI_DOCKERHUB_AUTH}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg TAG=${TAG} --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination=${ACCOUNT}/${CI_PROJECT_NAME}:${CI_PIPELINE_IID} --destination=${ACCOUNT}/${CI_PROJECT_NAME}:${TAG}
  only:
    refs:
      - tags

build-master:
  stage: build
  services: []
  variables:
    TAG: ${CI_COMMIT_REF_NAME}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${CI_DOCKERHUB_AUTH}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg TAG=master --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/main --destination=${ACCOUNT}/${CI_PROJECT_NAME}:${CI_PIPELINE_IID} --destination=${ACCOUNT}/${CI_PROJECT_NAME}:master
  only:
    - main
  tags:
    - bacon2


buildx:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.12-dind
  before_script:
    - apk add --no-cache curl jq
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create --name mybuilder --use
    - docker buildx inspect --bootstrap
  script:
    - mkdir -p $HOME/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${CI_DOCKERHUB_AUTH}\"}}}" > $HOME/.docker/config.json
    - docker buildx ls
    - docker buildx use gitlab
    - docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm/v8 --push -t ${ACCOUNT}/${CI_PROJECT_NAME}:master . --file main
  only:
    - buildx
